trigger:
- master

stages:
  - stage: build
    jobs:
      - job: 'build'
        pool: 
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: package
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
          - script: echo 'build success'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '**/gameoflife-web/target/*.war'
              ArtifactName: drop
              
  - stage: deploy
    jobs:
      - job: 'installanduseterraform'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo 'install terrform'
          - script: echo 'executing terraform apply command'  
